---
- name: Create web root of Laravel sites
  file:
    path: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/public"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '0755'
    state: directory
  loop: "{{ wordpress_sites | dict2items | selectattr('value.type', 'defined') | selectattr('value.type', 'equalto', 'laravel') | list }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create shared folder of Laravel sites
  file:
    path: "{{ www_root }}/{{ item.key }}/shared"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '0755'
    state: directory
  loop: "{{ wordpress_sites | dict2items | selectattr('value.type', 'defined') | selectattr('value.type', 'equalto', 'laravel') | list }}"
  loop_control:
    label: "{{ item.key }}"

- name: Create storage and bootstrap/cache directories with write permissions
  file:
    path: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/{{ dir }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '0775'
    state: directory
  loop: "{{ wordpress_sites | dict2items | selectattr('value.type', 'defined') | selectattr('value.type', 'equalto', 'laravel') | list }}"
  loop_control:
    label: "{{ item.key }}"
  with_items:
    - storage
    - storage/app
    - storage/app/public
    - storage/framework
    - storage/framework/cache
    - storage/framework/sessions
    - storage/framework/views
    - storage/logs
    - bootstrap/cache
  loop_var: dir

- name: Change site owner to user
  file:
    path: "{{ www_root }}/{{ item.key }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    state: directory
    recurse: yes
  loop: "{{ wordpress_sites | dict2items | selectattr('value.type', 'defined') | selectattr('value.type', 'equalto', 'laravel') | list }}"
  loop_control:
    label: "{{ item.key }}"
  when: chown_site_directory | default(false)