---
- name: Copy SSL cert
  copy:
    src: "{{ item.value.ssl.cert }}"
    dest: "{{ nginx_ssl_path }}/{{ item.value.ssl.cert | basename }}"
    mode: '0640'
  loop: "{{ wordpress_sites | dict2items | selectattr('value.type', 'defined') | selectattr('value.type', 'equalto', 'laravel') | list }}"
  loop_control:
    label: "{{ item.key }}"
  when: ssl_enabled and item.value.ssl.cert is defined
  notify: reload nginx

- name: Copy SSL key
  copy:
    src: "{{ item.value.ssl.key }}"
    dest: "{{ nginx_ssl_path }}/{{ item.value.ssl.key | basename }}"
    mode: '0600'
  loop: "{{ wordpress_sites | dict2items | selectattr('value.type', 'defined') | selectattr('value.type', 'equalto', 'laravel') | list }}"
  loop_control:
    label: "{{ item.key }}"
  when: ssl_enabled and item.value.ssl.key is defined
  notify: reload nginx

- import_tasks: "{{ playbook_dir }}/roles/common/tasks/disable_challenge_sites.yml"

- name: Create Laravel configuration for Nginx
  template:
    src: "{{ item.value.nginx_laravel_site_conf | default(nginx_laravel_site_conf) }}"
    dest: "{{ nginx_path }}/sites-available/{{ item.key }}.conf"
    mode: '0644'
  loop: "{{ wordpress_sites | dict2items | selectattr('value.type', 'defined') | selectattr('value.type', 'equalto', 'laravel') | list }}"
  loop_control:
    label: "{{ item.key }}"
  notify: reload nginx
  tags: nginx-includes

- name: Enable Laravel site
  file:
    src: "{{ nginx_path }}/sites-available/{{ item.key }}.conf"
    dest: "{{ nginx_path }}/sites-enabled/{{ item.key }}.conf"
    owner: root
    group: root
    state: link
  loop: "{{ wordpress_sites | dict2items | selectattr('value.type', 'defined') | selectattr('value.type', 'equalto', 'laravel') | list }}"
  loop_control:
    label: "{{ item.key }}"
  notify: reload nginx