# Documentation: https://roots.io/trellis/docs/local-development/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites/
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  example.com:
    site_hosts:
      - canonical: example.test
        redirects:
          - www.example.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@example.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    xmlrpc:
      enabled: false
  laravel-app.com:
    # Merged from laravel_sites.yml
    type: laravel # Specify that this is a Laravel site
    site_hosts:
      - canonical: laravel-app.test
        redirects:
          - www.laravel-app.test
    local_path: ../laravel # path targeting local Laravel project directory
    admin_email: admin@laravel-app.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    env:
      APP_NAME: "Laravel App"
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://laravel-app.test
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_DRIVER: sync
